package choir.api;

public enum Capability {
	OPTIONS_REGISTRATION,
	OPTIONS_GLOBAL_PERSISTENCE,
	OPTIONS_MAIN_MENU_UI,
	OPTIONS_IN_GAME_UI,
	ROOM_REGISTRATION_SPIKE,
	ROOM_REGISTRATION_V1,
	ROOM_PASSIVE_DECORATION_REGISTRATION,
	ROOM_PROVIDER_REQUIRED_SAVE_POLICY,
	CORE_MANIFESTS,
	CORE_DEPENDENCY_GRAPH,
	CORE_LIFECYCLE_EVENTS,
	CORE_PATCH_COMPOSITION,
	RACE_DATA_BACKED_REGISTRATION,
	RACE_BOOST_PATCHING,
	RACE_FOOD_PREFERENCE_PATCHING,
	RACE_DRINK_PREFERENCE_PATCHING,
	RACE_TEXT_PATCHING,
	RACE_RELATIONSHIP_PATCHING,
	RACE_NUMERIC_ATTRIBUTE_PATCHING,
	RACE_STANDING_PATCHING,
	RACE_HOME_RESOURCE_REQUIREMENTS,
	COMBAT_TACTICAL_DAMAGE_MULTIPLIERS,
	PRODUCTION_MULTI_OUTPUT_ROOMS,
	STORAGE_MULTI_RESOURCE_TILES
}
