manifest.version=1
game.version=0.71.44
game.jar.sha256=fe0137c05408e5ee9e31f06fc44fe37a5d4372d9c985b280f0852d1347c0224b
sources.jar.sha256=a3fc2aa9f4be31aec0616a5030a656ac49a6011343b7e91395c7bac0b9dfb0a5
validated.utc=2026-07-12T22:05:10Z

target.live.source.0.entry=init/resources/RESOURCES.java
target.live.source.0.sha256=95f41b46dd29c259df4fee151e73336b73a490069d4f80d2238857fbe06d3b1e
target.live.source.1.entry=init/resources/RESOURCE.java
target.live.source.1.sha256=5edaec2424e94c014a462e81f32be6f9a9a78f544db5479fa879bbe7ca9c13ac
target.live.source.2.entry=util/keymap/RMAP.java
target.live.source.2.sha256=0ac2756fa13e0140d0dab3f56831f351ce5988008c9f0f608fb7ef02fb3b646a
target.live.family.count=3
target.live.family.aggregate.sha256=3eff672fcaf490c14f057a78f499042be89240b467712aa86c88a242a6a9580d
target.live.class.0=init/resources/RESOURCE.class|6d5af3827a46b5622e0e7cf63da58759e8e8e0d345a1704f334593c0b46e0e03
target.live.class.1=init/resources/RESOURCES.class|55c337c54b1fe251da0998722d6b43f20238ab6a06ce8c51de99fc0c00329271
target.live.class.2=util/keymap/RMAP.class|c28840a00c283b0e2af2853f1b47fe43ab35e17adc56e3739622989f512725d5

required.live.0=init.resources.RESOURCES|ALL|()Lsnake2d/util/sets/LIST;
required.live.1=init.resources.RESOURCES|map|()Lutil/keymap/RMAPS;
required.live.2=init.resources.RESOURCE|key|()Ljava/lang/String;
required.live.3=init.resources.RESOURCE|index|()I
required.live.4=util.keymap.RMAP|tryGet|(Ljava/lang/String;)Lutil/keymap/MAPPED;
required.live.field.0=init.resources.RESOURCE|key|Ljava/lang/String;
required.live.field.1=init.resources.RESOURCE|category|I

target.stockpile.source.entry=settlement/room/infra/stockpile/Gui.java
target.stockpile.source.sha256=9f5720c42374db1a89380e32e434af199b7ed498cae820541da5feb79372cd1c
target.stockpile.family.count=24
target.stockpile.family.aggregate.sha256=04681f1cf8a6b3bac353ada90dcde068ea9a8c254beab8658b7a0c2b26968dd5
target.stockpile.class.0=settlement/room/infra/stockpile/Gui$1.class|282035bac6d805eb3c84a2be8648092ebcb635cabd6d63fb04c5fc14b926abda
target.stockpile.class.1=settlement/room/infra/stockpile/Gui$2.class|77887a935225a5a3bfaf39a5d23a7ebbc9a698f60c3de6061bdd370df0e902fb
target.stockpile.class.2=settlement/room/infra/stockpile/Gui$3.class|3429561997f584b0880d7c5ee56cc31530d315bb5ef03706abb0fa1b23826f02
target.stockpile.class.3=settlement/room/infra/stockpile/Gui$4.class|44cc151ef6c0b69e19c12d11389f5d77bb2c19abacccc3b2fca9572ae4b509fc
target.stockpile.class.4=settlement/room/infra/stockpile/Gui$5.class|0c88d15f41c6873348795086c6be81be575583cf831ac1ddccd367226c67b4c7
target.stockpile.class.5=settlement/room/infra/stockpile/Gui$6.class|b4598e16d5609e5f043e05a44d4b43bc10eec2e0babb753f54b64c2f4eed0aa4
target.stockpile.class.6=settlement/room/infra/stockpile/Gui$7.class|e36970465aa4f753134248236f8f0bdbd8ae566f1ee12c9a4db6abcb0214df6e
target.stockpile.class.7=settlement/room/infra/stockpile/Gui$8.class|716cc47aa71267c4e8d28c8d2873e9308c53eeb615d4f3f4b0fc4bd529120709
target.stockpile.class.8=settlement/room/infra/stockpile/Gui$9.class|6417489b2ffe457b5841981ee241d01065e7b9e2f3960ab9ca284a32dc9ea0a9
target.stockpile.class.9=settlement/room/infra/stockpile/Gui$ResArea2$1.class|f92f1a57568ca8b42a342c879c170f3a86b330b5d85da203a11c9a20db15efaf
target.stockpile.class.10=settlement/room/infra/stockpile/Gui$ResArea2$2.class|c56b472d7c7308e6e91e29983469cf69bafa45382daf2d0a18309d217e78b3a8
target.stockpile.class.11=settlement/room/infra/stockpile/Gui$ResArea2$3.class|5023d4135dc2adc39baa1e6a51cd6d0e00ff85b98d8b8728be70bd110235eb12
target.stockpile.class.12=settlement/room/infra/stockpile/Gui$ResArea2$4.class|38ea725d11db80c9c248ff37b094e13c8934450ec9c3e712a87360eb58d47fd8
target.stockpile.class.13=settlement/room/infra/stockpile/Gui$ResArea2$5.class|61e2a10379760dbb5d31b6670826241d18cf35e16213c1f4a0386001caab3999
target.stockpile.class.14=settlement/room/infra/stockpile/Gui$ResArea2$6.class|bdb08e680d4dd2581e5121441c6175b604e76acf74c1cbdfb50bc4939699e9b4
target.stockpile.class.15=settlement/room/infra/stockpile/Gui$ResArea2$7.class|8fc22c90f518d623a36bf4070ee1aa5fe0a5d72dc4827d4d8486a8d56d6115bd
target.stockpile.class.16=settlement/room/infra/stockpile/Gui$ResArea2$ResLineDetailed$1.class|f29957957c00e8b8389d5322814a7473ca21e9d75f2a4370d321c318458d79b8
target.stockpile.class.17=settlement/room/infra/stockpile/Gui$ResArea2$ResLineDetailed$2.class|a9bd0587e5d055bb5729cf980fb020a13a6a7be359b132aa83fa76567272a911
target.stockpile.class.18=settlement/room/infra/stockpile/Gui$ResArea2$ResLineDetailed$3.class|da6ded05248278342229e0c7d34342362e7cbe3b02e07ac4ce8144b65ffd9147
target.stockpile.class.19=settlement/room/infra/stockpile/Gui$ResArea2$ResLineDetailed$4.class|9a5b79e1bfd5ce0b8648bcfd4b28195227a50e40fe233994d88c7b79841dfaa7
target.stockpile.class.20=settlement/room/infra/stockpile/Gui$ResArea2$ResLineDetailed$5.class|29297bc06f9b24d1df4cbea9e48052fa3fce22c4a1ef108be0f61a2658869a3e
target.stockpile.class.21=settlement/room/infra/stockpile/Gui$ResArea2$ResLineDetailed.class|9ee9b1178a869287926eb06495eaf4182603b812215bd6f9328a2b7dfd711d05
target.stockpile.class.22=settlement/room/infra/stockpile/Gui$ResArea2.class|b45d8534149b330f7a395b4850d17b3bf7f053cd368d793ac0ff3e2a990ff115
target.stockpile.class.23=settlement/room/infra/stockpile/Gui.class|3aef18afbdf4cf01e7bea7db61dac4133ee5bdef232839b33d10bb775e1b0789

target.right.source.entry=view/sett/ui/right/UIMiniResources.java
target.right.source.sha256=e83e97de1b6313a34888d48e390399f8f1a4a3e2400c78a24534675b364dce4e
target.right.family.count=13
target.right.family.aggregate.sha256=58d3adf45435dca58e9550dad3f25ff6774833bccf04e2acaf25325e35c98bf5
target.right.class.0=view/sett/ui/right/UIMiniResources$1.class|8142f7aadc3b4416d588c2701f32f72e636fed3ccdfc5470de0053558a645ef4
target.right.class.1=view/sett/ui/right/UIMiniResources$2.class|6002dd463977a35a9310944a771c053a4da7efbe4d2f139d16cf0f1694d44eb9
target.right.class.2=view/sett/ui/right/UIMiniResources$3.class|ee858f6ef41389ce6fa2496907ca2bd2ca0421f40b24ed7bce6fdbad71386afd
target.right.class.3=view/sett/ui/right/UIMiniResources$4.class|ef9c6e5a6d342fa2e763264490d73b533a71c73e84e01fdea8aa7acc7aec1b33
target.right.class.4=view/sett/ui/right/UIMiniResources$Full$1.class|8ed51ae03ebf4b524ba08dfb61e9f8656486df56e9e3a2e4f97be0cf5d8274d5
target.right.class.5=view/sett/ui/right/UIMiniResources$Full$2.class|c1dabd7be28cb85e6242910a31dfe7c75a4b06027658ca4c2718f2802cc84a18
target.right.class.6=view/sett/ui/right/UIMiniResources$Full$3.class|910eb0c4dc67caa541cd3f4617c5ade65a55f4b3c85f47895aa9ec81c5712a9e
target.right.class.7=view/sett/ui/right/UIMiniResources$Full.class|df00ce037a9e48dc050b90695df7c175b8be8a41549b1e9b46d161d5cad6a2b3
target.right.class.8=view/sett/ui/right/UIMiniResources$Mini$1.class|14449a3b457e5558a91e0e66bba3b1282dc9cfb4b8a1988b9a4066b1089d3bbf
target.right.class.9=view/sett/ui/right/UIMiniResources$Mini$2.class|0ac582345e56dbd250ef48a95cc1b40f44fce0441af2adcf09f8b0c9c0d0cc8e
target.right.class.10=view/sett/ui/right/UIMiniResources$Mini$3.class|ebb88b77c6fd1c562d99305fb6d6b002d293478590f9bd34aa8dabf63f9956cb
target.right.class.11=view/sett/ui/right/UIMiniResources$Mini.class|e2f6a4039c39cb974abcbcf766f2f91a96dacd1756cdd4d6da2108549c2e28f9
target.right.class.12=view/sett/ui/right/UIMiniResources.class|0bd0a61519c3aa3359ed8e2db2eefe9f41ea06a7a0af2f8a7a7868fc4b4dc29a

required.stockpile.0=settlement.room.infra.stockpile.Gui|<init>|(Lsettlement/room/infra/stockpile/ROOM_STOCKPILE;)V
required.stockpile.1=settlement.room.infra.stockpile.Gui$ResArea2|<init>|(Lutil/data/GETTER;I)V
required.stockpile.2=settlement.room.infra.stockpile.Gui$ResArea2|makeTable|(Lutil/data/GETTER;Lsnake2d/util/misc/ACTION;)Lsnake2d/util/gui/GuiSection;
required.stockpile.3=settlement.room.infra.stockpile.Gui$ResArea2$ResLineDetailed|<init>|(Lutil/data/GETTER;Lutil/data/GETTER;Lsnake2d/util/misc/ACTION;)V
required.stockpile.4=settlement.room.infra.stockpile.Gui$ResArea2$ResLineDetailed|click|()Z
required.stockpile.5=settlement.room.infra.stockpile.Gui$ResArea2$ResLineDetailed|hoverInfoGet|(Lsnake2d/util/gui/GUI_BOX;)V
required.stockpile.6=settlement.room.infra.stockpile.Gui|appendPanel|(Lsnake2d/util/gui/GuiSection;Lutil/gui/misc/GGrid;Lutil/data/GETTER;II)V
required.stockpile.7=settlement.room.infra.stockpile.Gui|appendTableButt|(Lsnake2d/util/gui/GuiSection;Lutil/data/GETTER;)V
required.stockpile.8=settlement.room.infra.stockpile.Gui|problem|(Lsettlement/room/infra/stockpile/StockpileInstance;Lsnake2d/util/sets/Stack;Lsnake2d/util/sets/LISTE;Lsnake2d/util/sets/LISTE;)V
required.stockpile.9=settlement.room.infra.stockpile.Gui|hover|(Lutil/gui/misc/GBox;Lsettlement/room/infra/stockpile/StockpileInstance;)V
required.stockpile.10=settlement.room.infra.stockpile.Gui|appendTableFilters|(Lsnake2d/util/sets/LISTE;Lsnake2d/util/sets/LISTE;Lsnake2d/util/sets/LISTE;)V
required.stockpile.11=settlement.room.infra.stockpile.Gui|hover|(Lsnake2d/util/gui/GUI_BOX;Lsettlement/room/infra/stockpile/StockpileInstance;Linit/resources/RESOURCE;)V
required.stockpile.12=settlement.room.infra.stockpile.Gui$ResArea2|render|(Lsnake2d/SPRITE_RENDERER;F)V
required.stockpile.13=settlement.room.infra.stockpile.Gui$ResArea2$ResLineDetailed|render|(Lsnake2d/SPRITE_RENDERER;F)V
required.stockpile.field.0=settlement.room.infra.stockpile.Gui$ResArea2|current|Lsnake2d/util/sets/ArrayList;
required.stockpile.field.1=settlement.room.infra.stockpile.Gui$ResArea2$ResLineDetailed|res|Lutil/data/GETTER;
required.stockpile.field.2=settlement.room.infra.stockpile.Gui$ResArea2|g|Lutil/data/GETTER;
required.stockpile.field.3=settlement.room.infra.stockpile.Gui$ResArea2|lastOpen|Lsettlement/room/infra/stockpile/StockpileInstance;
required.stockpile.field.4=settlement.room.infra.stockpile.Gui$ResArea2|pop|Lsnake2d/util/gui/GuiSection;
required.stockpile.field.5=settlement.room.infra.stockpile.Gui$ResArea2$ResLineDetailed|prev|Linit/resources/RESOURCE;
required.stockpile.field.6=settlement.room.infra.stockpile.Gui$ResArea2$ResLineDetailed|g|Lutil/data/GETTER;

required.right.0=view.sett.ui.right.UIMiniResources|<init>|(II)V
required.right.1=view.sett.ui.right.UIMiniResources$Mini|<init>|(I)V
required.right.2=view.sett.ui.right.UIMiniResources$Full|<init>|(I)V
required.right.3=view.sett.ui.right.UIMiniResources|resBody|(Linit/resources/RESOURCE;)Lsnake2d/util/gui/GuiSection;
required.right.4=view.sett.ui.right.UIMiniResources|mini|(Linit/resources/RESOURCE;)Lsnake2d/util/gui/renderable/RENDEROBJ;
required.right.5=view.sett.ui.right.UIMiniResources|big|(Linit/resources/RESOURCE;)Lsnake2d/util/gui/renderable/RENDEROBJ;
required.right.6=view.sett.ui.right.UIMiniResources|stat|(Linit/resources/RESOURCE;)Lsnake2d/util/gui/renderable/RENDEROBJ;
required.right.7=view.sett.ui.right.UIMiniResources|render|(Lsnake2d/SPRITE_RENDERER;F)V
required.right.field.0=view.sett.ui.right.UIPanelRightSett|resources|Lview/sett/ui/right/UIMiniResources;
required.right.field.1=view.sett.ui.right.UIMiniResources|mini|Lsnake2d/util/gui/GuiSection;
required.right.field.2=view.sett.ui.right.UIMiniResources|full|Lsnake2d/util/gui/GuiSection;
required.right.field.3=view.sett.ui.right.UIMiniResources$Mini|t|Lutil/data/INT$INTE;
required.right.field.4=view.sett.ui.right.UIMiniResources$Full|t|Lutil/data/INT$INTE;
